# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/bnagy/gapstone"
  version = "3.0.3"

[[constraint]]
  name = "github.com/chzyer/readline"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/felberj/ramfs"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  name = "github.com/jroimartin/gocui"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/keystone-engine/keystone"

[[constraint]]
  branch = "master"
  name = "github.com/lunixbochs/argjoy"

[[constraint]]
  branch = "master"
  name = "github.com/lunixbochs/capstr"

[[constraint]]
  branch = "master"
  name = "github.com/lunixbochs/fvbommel-util"

[[constraint]]
  branch = "master"
  name = "github.com/lunixbochs/ghostrace"

[[constraint]]
  branch = "master"
  name = "github.com/lunixbochs/luaish"

[[constraint]]
  branch = "master"
  name = "github.com/lunixbochs/luaish-luar"

[[constraint]]
  name = "github.com/lunixbochs/readline"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/lunixbochs/struc"

[[constraint]]
  branch = "master"
  name = "github.com/mgutz/ansi"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/shibukawa/configdir"

[[constraint]]
  branch = "master"
  name = "github.com/unicorn-engine/unicorn"

[prune]
  go-tests = true
  unused-packages = true
